### ISSUE TITLE
[Bug]: 在某些情况下传送到另一个很远的未加载区块，导致崩服

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LeviOptimize#4]
### Describe the bug

使用高频活塞然后传送到另一个很远的未加载区块，导致崩服

[crash.zip](https://github.com/LiteLDev/LeviOptimize/files/14523137/crash.zip)

![image](https://github.com/LiteLDev/LeviOptimize/assets/99462074/33e776d9-78da-4034-bf72-bf822c0f5f3d)

### To Reproduce

使用高频活塞然后传送到另一个很远的未加载区块，导致崩服

### Expected behavior

不崩服

### Platform

Win10

### BDS Version

1.20.62.02

### LeviLamina Version

0.9.2

### Version

0.1.6

**Comment by killcerr** [comment]
您可以提供一个更加详细的复现过程吗？
（最好有视频）

**Comment by yufengya0420** [comment]
> 您可以提供一个更加详细的复现过程吗？ 我这里无法复现。

触发方式有点随机性，我当时是做了一个双倍速卸货机运行当中然后传送到一个比较远的地方直接就崩服了

**Comment by killcerr** [comment]
可能与MCPE-179440有关
