### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by XSLG123** [LiteLDev/LeviOptimize#6]
### Describe the bug

崩
[minidump_2024-04-06_10-50-38.dmp](https://github.com/LiteLDev/LeviOptimize/files/14892489/minidump_2024-04-06_10-50-38.dmp)
[minidump_2024-04-06_12-58-42.dmp](https://github.com/LiteLDev/LeviOptimize/files/14892490/minidump_2024-04-06_12-58-42.dmp)
[trace_2024-04-06_10-50-38.log](https://github.com/LiteLDev/LeviOptimize/files/14892491/trace_2024-04-06_10-50-38.log)
[trace_2024-04-06_12-58-42.log](https://github.com/LiteLDev/LeviOptimize/files/14892492/trace_2024-04-06_12-58-42.log)

### To Reproduce

开了多个端，关服的时候崩

### Expected behavior

速修，已发癫

### Platform

windows10

### BDS Version

1.20.73

### LeviLamina Version

10.0.5

### Version

0.2.1

**Comment by Dofes** [comment]
请尝试将config/config.json中的"playerLookupOpt": true,改成false，然后运行观察是否崩溃

**Comment by Dofes** [comment]
看完了
第一个dmp是fac有冲突，暂时不知道是怎么回事
第二个是蜜蜂崩服，这个没啥关系，是原版bug
https://blog.litebds.com/2023/07/26/original-fix-BeeCrash/
